CREATE DATABASE IF NOT EXISTS users CHARSET=utf8mb4;
USE users;
CREATE TABLE IF NOT EXISTS users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nickname VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	psswrd VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS category(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;